### ISSUE TITLE
No archive_node.py files found

### ISSUE THREAD

**Issue by iyaqiao** [xiexiexiaoxiexie/Intelligent-LiDAR-Navigation-LLM-as-Copilot#1]
Thank you for your work，I tried to run this project but failed，because of the lack of archive_node.py

**Comment by xiexiexiaoxiexie** [comment]
Hi, thanks to be interested in our research, the archive_node.py is only used to save topics into a file. For now, you could just delete it from the launch file, I will delete this node from launch file later, thanks for pointing that out :)
